using Content.Client.UserInterface.Controls;
using Content.Shared._BPL.Pathfinding;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._BPL.Pathfinding;

[GenerateTypedNameReferences]
public sealed partial class DeliveryBoyWindow : FancyWindow
{
    public event Action<NetEntity>? OnConfirm;

    private readonly List<DeliveryBoyBeaconEntry> _beacons = [];
    private NetEntity? _selected;

    public DeliveryBoyWindow()
    {
        RobustXamlLoader.Load(this);

        SearchBar.OnTextChanged += _ => RebuildList();
        BeaconList.OnItemSelected += args =>
        {
            _selected = BeaconList[args.ItemIndex].Metadata is NetEntity beacon ? beacon : null;
            ConfirmButton.Disabled = _selected == null;
        };
        BeaconList.OnItemDeselected += _ =>
        {
            _selected = null;
            ConfirmButton.Disabled = true;
        };
        ConfirmButton.OnPressed += _ =>
        {
            if (_selected is { } beacon)
                OnConfirm?.Invoke(beacon);
        };
    }

    public void Populate(List<DeliveryBoyBeaconEntry> beacons)
    {
        _beacons.Clear();
        _beacons.AddRange(beacons);
        _selected = null;
        ConfirmButton.Disabled = true;
        RebuildList();
    }

    private void RebuildList()
    {
        var filter = SearchBar.Text.Trim();
        BeaconList.Clear();

        foreach (var entry in _beacons)
        {
            if (filter.Length > 0 &&
                entry.Label.IndexOf(filter, StringComparison.CurrentCultureIgnoreCase) < 0)
            {
                continue;
            }

            var item = BeaconList.AddItem(entry.Label);
            item.Metadata = entry.Beacon;
            if (_selected == entry.Beacon)
                item.Selected = true;
        }

        var any = BeaconList.Count > 0;
        BeaconList.Visible = any;
        EmptyLabel.Visible = !any;
        EmptyLabel.Text = Loc.GetString(_beacons.Count == 0
            ? "delivery-boy-window-empty"
            : "delivery-boy-window-no-match");
        if (!any)
        {
            _selected = null;
            ConfirmButton.Disabled = true;
        }
    }
}
